### ISSUE TITLE
node6环境测试用例报错

### ISSUE THREAD

**Issue by xuexb** [xuexb/fs-grep#3]
```
  1) fs-grep exec empty path:
     ENOENT: no such file or directory, scandir '/home/travis/build/xuexb/fs-grep/empty'
  Error: ENOENT: no such file or directory, scandir 'empty'
      at Error (native)
      at Object.fs.readdir (node_modules/mock-fs/node/fs-6.0.0.js:851:11)
      at Glob._readdir (node_modules/glob/glob.js:541:6)
      at Glob._processGlobStar (node_modules/glob/glob.js:619:8)
      at Glob._process (node_modules/glob/glob.js:360:10)
      at new Glob (node_modules/glob/glob.js:167:10)
      at glob (node_modules/glob/glob.js:74:10)
      at Grep._init (src/index.js:9:2323)
      at new Grep (src/index.js:9:1985)
      at exec (src/index.js:9:6469)
      at Context.<anonymous> (index.js:118:20)
  2) fs-grep exec not found:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

  3) fs-grep exec end result:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

  4) fs-grep exec line:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by xuexb** [comment]
linux和windows都报错

**Comment by xuexb** [comment]
查到原因了，由于`node-glob`依赖包引起，这是她的测试：[linux test case](https://travis-ci.org/xuexb/node-glob/jobs/127363276)、[windows test case](https://ci.appveyor.com/project/xuexb/node-glob/build/1/job/jihqkkkm8ct66gnm) ，在node6.0环境下均没有通过～
